{
 "title": "EmployeeTracking",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Present Today",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "PackingDispatchDB",
     "rawSql": "SELECT COUNT(*) AS \"Present Count\"\r\nFROM Employees\r\nWHERE SUBSTRING(attendance, DAY(CURDATE()), 1) = '1';\r\n"
    }
   ]
  },
  {
   "title": "Absent Today",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "PackingDispatchDB",
     "rawSql": "SELECT COUNT(*) AS \"Present Count\"\r\nFROM Employees\r\nWHERE SUBSTRING(attendance, DAY(CURDATE()), 1) = '0';\r\n"
    }
   ]
  },
  {
   "title": "Qualification Distribution",
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 18, "x": 6, "y": 0 },
   "targets": [
    {
     "dataset": "PackingDispatchDB",
     "rawSql": "SELECT \r\n    education AS \"Qualification\", \r\n    COUNT(*) AS \"Total Employees\"\r\nFROM \r\n    Employees\r\nGROUP BY \r\n    qualification\r\nORDER BY \r\n    \"Total Employees\" DESC;\r\n"
    }
   ]
  },
  {
   "title": " Total Number of Employees by Gender",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 4 },
   "targets": [
    {
     "dataset": "PackingDispatchDB",
     "rawSql": "SELECT \r\n    gender AS \"Gender\", \r\n    COUNT(*) AS \"Total Employees\"\r\nFROM \r\n    Employees\r\nGROUP BY \r\n    gender\r\nORDER BY \r\n    \"Total Employees\" DESC;\r\n"
    }
   ]
  },
  {
   "title": "Ageing",
   "type": "bargauge",
   "gridPos": { "h": 11, "w": 6, "x": 6, "y": 7 },
   "targets": [
    {
     "dataset": "PackingDispatchDB",
     "rawSql": "SELECT \r\n    CASE\r\n        WHEN ageing < 30 THEN 'Less than a month'\r\n        WHEN ageing >= 30 AND ageing < 90 THEN '1 month to 3 months'\r\n        WHEN ageing >= 90 AND ageing < 180 THEN '3 months to 6 months'\r\n        ELSE 'More than 6 months'\r\n    END AS ageing_category,\r\n    COUNT(*) AS employee_count\r\nFROM Employees\r\nGROUP BY ageing_category\r\nORDER BY FIELD(ageing_category, 'Less than a month', '1 month to 3 months', '3 months to 6 months', 'More than 6 months');\r\n"
    }
   ]
  },
  {
   "title": "Shift Wise Attendance",
   "type": "bargauge",
   "gridPos": { "h": 11, "w": 3, "x": 12, "y": 7 },
   "targets": [
    {
     "dataset": "PackingDispatchDB",
     "rawSql": "SELECT \r\n    shift,\r\n    COUNT(*) AS \"Present Count\"\r\nFROM \r\n    Employees\r\nWHERE \r\n    SUBSTRING(attendance, DAY(CURDATE()), 1) = '1'\r\n    AND shift IS NOT NULL  \r\nGROUP BY \r\n    shift;\r\n"
    }
   ]
  },
  {
   "title": "Throughput by Gender",
   "type": "piechart",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 11 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "PackingDispatchDB",
     "rawSql": "SELECT \r\n    gender AS \"Gender\",\r\n    AVG(throughput) AS \"Average Throughput\"\r\nFROM \r\n    Employees\r\nGROUP BY \r\n    gender\r\nORDER BY \r\n    \"Average Throughput\" DESC;\r\n"
    }
   ]
  },
  {
   "title": "Throughput",
   "type": "piechart",
   "gridPos": { "h": 20, "w": 6, "x": 0, "y": 18 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "PackingDispatchDB",
     "rawSql": "SELECT \r\n  employeeid AS \"Employee Name\", \r\n  throughput AS \"Throughput\" \r\nFROM Employees\r\n"
    }
   ]
  }
 ]
}